spring:
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
    servlet:
      path: /


  datasource:
      url: jdbc:mariadb://shopping-mall.c197xgtjr5yn.ap-northeast-2.rds.amazonaws.com:3306/shop?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: rkswlska2!
      charset: UTF-8
      collation: UTF-8_general_ci


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.hy.shop


logging:
  level:
    org.springframework.security: DEBUG
